version: '3.9'
services:
  laurelTools:
    restart: unless-stopped
    image: maximummaxx/laureltools:latest
    container_name: laureltools
    hostname: laureltools
    ports:
    - '5000:5000'
    expose:
      - 5000
    networks:
      laurelWeb:
    labels:
        - traefik.enable=true
        - traefik.http.routers.tools.entrypoints=web,websecure
        - traefik.http.routers.tools.rule=Host("tools.laurel.community")
        - traefik.http.routers.tools.tls=true
        - traefik.http.routers.tools.tls.certresolver=production
    env_file:
        - stack.env
networks:
  laurelWeb:
    external: true
    name: "laurelWeb"
