version: '3.9'
services:
  laurelTools:
    restart: unless-stopped
    image: maximummaxx/laureltools:latest
    container_name: laureltools
    hostname: laureltools
    ports:
    - '5000:5000'
    networks:
      laurelWeb:
networks:
  laurelWeb:
    external: true
    name: "laurelWeb"