version: '3.9'
services:
  laurelTools:
    image: maximummaxx/laureltools:latest
    container_name: laureltools
    ports:
    - '8090:5000'
    networks:
      laurelWeb:
networks:
  laurelWeb:
    external: true
    name: "laurelWeb"